apiVersion: apps/v1
kind: Deployment
metadata:
  name: server_deployment
  labels:
    app: static-site
spec:
  replicas: 5
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: static-site
        image: nasimc99/simple_server
        imagePullPolicy: Always
        ports:
        - containerPort: 80